#ifndef _NAME_MANAGER_
#define _NAME_MANAGER_

#include <string>
using namespace std;

#define CREATE_VALUE(NAME) static const string NAME = #NAME;
#define CREATE_VALUE_WITH_VALUE(NAME, VALUE) static const string NAME = VALUE;

namespace NAME_MGR
{
	CREATE_VALUE(G_JUMP);
	CREATE_VALUE(G_ENTER);
	CREATE_VALUE(G_ELEVATOR);
	CREATE_VALUE(G_JETPACK);
	CREATE_VALUE(G_DROP);
	CREATE_VALUE(G_TRAVERSE);
	CREATE_VALUE(G_MEGA);
	CREATE_VALUE(G_MARIO);
	CREATE_VALUE(G_KIRBY);
}
#endif //_NAME_MANAGER_